import {
  catalog_1,
  catalog_2,
  catalog_3,
  catalog_4,
  catalog_5,
  product_1,
  product_2,
  product_3,
  product_4,
  product_5,
  product_6,
  product_7,
  product_8,
} from "../assets";

export const ProductService = {
  getProductsData() {
    return [
      {
        id: 1,
        categoryId: 1,
        name: "Beat",
        image: product_1,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 2,
        categoryId: 1,
        name: "Bamboo Watch",
        image: product_2,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 3,
        categoryId: 1,
        name: "Bamboo Watch",
        image: product_3,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 4,
        categoryId: 1,
        name: "Bamboo Watch",
        image: product_4,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 5,
        categoryId: 1,
        name: "Bamboo Watch",
        image: product_5,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 6,
        categoryId: 1,
        name: "Bamboo Watch",
        image: product_6,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 7,
        categoryId: 1,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 8,
        categoryId: 1,
        name: "Bamboo Watch",
        image: product_8,
        description: "Product Description",
        price: 65,
        category: "Power Distribution",
        rating: 5,
      },
      {
        id: 9,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_8,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },
      {
        id: 10,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_1,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },
      {
        id: 11,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_4,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },
      {
        id: 12,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_6,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },
      {
        id: 13,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },
      {
        id: 14,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_2,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },
      {
        id: 15,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },
      {
        id: 16,
        categoryId: 2,
        name: "Bamboo Watch",
        image: product_5,
        description: "Product Description",
        price: 65,
        category: "Electrical Materials",
        rating: 5,
      },{
        id: 17,
        categoryId: 3,
        name: "Beat",
        image: product_3,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 18,
        categoryId: 3,
        name: "Bamboo Watch",
        image: product_2,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 19,
        categoryId: 3,
        name: "Bamboo Watch",
        image: product_6,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 20,
        categoryId: 3,
        name: "Bamboo Watch",
        image: product_4,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 21,
        categoryId: 3,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 22,
        categoryId: 3,
        name: "Bamboo Watch",
        image: product_8,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 23,
        categoryId: 3,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 24,
        categoryId: 3,
        name: "Bamboo Watch",
        image: product_1,
        description: "Product Description",
        price: 65,
        category: "Final Distribution",
        rating: 5,
      },
      {
        id: 25,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_8,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 26,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_1,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 27,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_4,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 28,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_6,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 29,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 30,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_2,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 31,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 32,
        categoryId: 4,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Power Supply",
        rating: 5,
      },
      {
        id: 33,
        categoryId: 5,
        name: "Beat",
        image: product_3,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
      {
        id: 34,
        categoryId: 5,
        name: "Bamboo Watch",
        image: product_5,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
      {
        id: 35,
        categoryId: 5,
        name: "Bamboo Watch",
        image: product_7,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
      {
        id: 36,
        categoryId: 5,
        name: "Bamboo Watch",
        image: product_5,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
      {
        id: 37,
        categoryId: 5,
        name: "Bamboo Watch",
        image: product_1,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
      {
        id: 38,
        categoryId: 5,
        name: "Bamboo Watch",
        image: product_2,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
      {
        id: 39,
        categoryId: 5,
        name: "Bamboo Watch",
        image: product_6,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
      {
        id: 40,
        categoryId: 5,
        name: "Bamboo Watch",
        image: product_1,
        description: "Product Description",
        price: 65,
        category: "Power Managment",
        rating: 5,
      },
    ];
  },
  getProductsCategory() {
    return [
      {
        id: 1,
        url: catalog_1,
        name: "Power Distribution",
        title: "Membership Organisations",
        description:
          "Our membership management software provides full automation of membership renewals and payments",
      },
      {
        id: 2,
        url: catalog_2,
        name: "Electrical Materials",
        title: "Membership Organisations",
        description:
          "Our membership management software provides full automation of membership renewals and payments",
      },
      {
        id: 3,
        url: catalog_3,
        name: "Final Distribution",
        title: "National Associations",
        description:
          "Our membership management software provides full automation of membership renewals and payments",
      },
      {
        id: 4,
        url: catalog_4,
        name: "Power Supply",
        title: "Clubs And Groups",
        description:
          "Our membership management software provides full automation of membership renewals and payments",
      },
      {
        id: 5,
        url: catalog_5,
        name: "Power Managment",
        title: "Clubs And Groups",
        description:
          "Our membership management software provides full automation of membership renewals and payments",
      },
    ];
  },
};
