export { default as Home } from './Home'
export { default as About } from './About'
export { default as News } from './News'
export { default as Branchs } from './Branchs'
export { default as Contact } from './Contact'
export { default as NewsDetail } from './NewsDetail'
export { default as ProductDetail } from './ProductDetail'
export { default as Detail } from './Detail'