export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as Slider } from "./Slider";
export { default as About } from "./About";
export { default as Comunity } from "./Comunity";
export { default as Catalog } from "./Catalog";
export { default as Product } from './Product'
export { default as Statistics } from './Statistics.jsx'
export { default as News } from './News'
